<script lang="ts">
	import { activeModal, showToast } from '$lib/stores';
	import { COURSES, PLATFORM_STATS, INSTITUTION_TYPES, type InstitutionType } from '$lib/data/courseData';
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';

	// Curriculum Browser State
	let selectedInst: InstitutionType = 'University';
	let courseSearch = '';

	$: filteredCourses = COURSES[selectedInst].filter(c =>
		c.toLowerCase().includes(courseSearch.toLowerCase())
	);

	function goToLab(course: string, mode: 'lab' | 'mock' = 'lab') {
		goto(`/exam-lab?course=${encodeURIComponent(course)}&inst=${encodeURIComponent(selectedInst)}&mode=${mode}`);
	}

	// Animated counters
	let counters = { institutions: 0, questions: 0, students: 0, passRate: 0 };
	let hasAnimated = false;

	function animateCounters() {
		if (hasAnimated) return;
		hasAnimated = true;
		const targets = { institutions: 550, questions: 250, students: 12, passRate: 89 };
		const duration = 1800;
		const start = performance.now();
		function step(now: number) {
			const elapsed = now - start;
			const progress = Math.min(elapsed / duration, 1);
			const ease = 1 - Math.pow(1 - progress, 3);
			counters = {
				institutions: Math.floor(targets.institutions * ease),
				questions: Math.floor(targets.questions * ease),
				students: Math.floor(targets.students * ease),
				passRate: Math.floor(targets.passRate * ease)
			};
			if (progress < 1) requestAnimationFrame(step);
		}
		requestAnimationFrame(step);
	}

	// FAQ
	let openFaq = -1;
	const faqs = [
		{
			q: 'How does the AI generate relevant exam questions for my specific course?',
			a: "CollegeCBT uses Anthropic's Claude AI, trained on vast academic literature and past examination materials. When you select your institution type, course, level, and topic, the system constructs a detailed academic prompt specifying your exact context. Claude generates questions accurate, contextual, and aligned with NUC, NBTE, or NCCE curriculum for that subject — freshly generated every time."
		},
		{
			q: 'Is CollegeCBT suitable for all Nigerian higher institutions?',
			a: "Yes. CollegeCBT covers all 309+ accredited universities (NUC); all 78+ polytechnics (NBTE); all 163+ Colleges of Education (NCCE); and Innovation Enterprise Institutions (IEIs). Whether you're studying 100 Level at a federal university, HND at a polytechnic, or NCE at a college of education, CollegeCBT has your content."
		},
		{
			q: 'What is the difference between Exam Lab and Mock Exam?',
			a: "The Exam Lab is an open-ended practice environment: one question at a time, with full explanations shown immediately. Ideal for learning. The Mock Exam simulates real examination conditions — timed at 90 seconds per question, auto-submitted on timeout. At the end, you receive a WAEC grade (A1–F9), performance analysis, and a question-by-question review."
		},
		{
			q: 'How does payment work? Can I pay in Naira?',
			a: "Yes — all pricing is in Nigerian Naira (₦). We support debit cards (Verve, Mastercard, Visa), bank transfer, USSD, and POS via Flutterwave and KoraPay. No dollar card required. The Free plan needs no payment at all. Student Pro is ₦5,000 per semester or ₦8,500 per year."
		},
		{
			q: 'What is the AI Readiness Score and how is it calculated?',
			a: "The AI Readiness Score (0–100) is a composite metric based on your correct-answer rate, consistency (streak), performance on timed vs. untimed sessions, and topic coverage. A score of 75+ indicates exam readiness. It updates after every session and generates your grade prediction and personalized study recommendations."
		},
		{
			q: 'What is "Results as a Service" (RaaS)?',
			a: "RaaS means we measure our success by your exam score. Our AI tracks your grade trajectory, predicts readiness, generates an Outcome Projection report, and provides targeted practice until you hit 75%. Pro students who complete 30+ mock exams and don't achieve 75% are eligible for a free semester extension — because your result is our result."
		}
	];

	// Features
	const features = [
		{ icon: '🤖', title: 'Claude AI Questions', desc: 'Unlimited exam questions generated by Anthropic\'s Claude — fresh, contextual, and curriculum-aligned every time.', color: '#7c3aed' },
		{ icon: '⏱️', title: 'Timed Mock Exams', desc: 'Realistic exam simulation with 90-second per-question timer, skip function, WAEC grading (A1–F9), and full review at the end.', color: '#84cc16' },
		{ icon: '📊', title: 'Results Intelligence', desc: 'AI Readiness Score (0–100), grade prediction, topic heatmaps, and national benchmarking for every student.', color: '#f59e0b' },
		{ icon: '🎯', title: 'Distractor Analysis', desc: 'Every wrong option explained — understand exactly why your answer was wrong and how to avoid the trap next time.', color: '#22d3ee' },
		{ icon: '🏛️', title: '550+ Institutions', desc: 'Universities (NUC), Polytechnics (NBTE), Colleges of Education (NCCE), and IEIs. Every level, every course.', color: '#a855f7' },
		{ icon: '📝', title: 'Theory Mode', desc: 'Essay questions with mark schemes, key points, and model answers aligned with examiner expectations.', color: '#e11d48' }
	];

	// Testimonials
	const testimonials = [
		{ quote: 'I failed DBMS in 200L. After 3 weeks with CollegeCBT\'s Exam Lab and Mock Exams, I scored 79% in my 300L resit. The distractor explanations are what made the difference.', name: 'Emeka Okonkwo', meta: 'Computer Science · 300L · UNN', grade: '🏆 A1 — 79% in DBMS', emoji: '👨🏾‍🎓', color: 'rgba(124,58,237,0.2)' },
		{ quote: 'As a pharmacy student at UNILAG, finding relevant practice questions was nearly impossible. CollegeCBT generated questions specific to Pharmacology at exactly my level. I went from 58% to 81%.', name: 'Fatima Abdullahi', meta: 'Pharmacy · 400L · UNILAG', grade: '🏆 A1 — 81% in Pharmacology', emoji: '👩🏽‍⚕️', color: 'rgba(132,204,22,0.15)' },
		{ quote: 'I\'m a HND Accountancy student at Yaba Tech and CollegeCBT is the first platform that actually has our level and courses. The mock exam timer prepared me mentally. I went from C4 to B2.', name: 'Chidi Nwosu', meta: 'Accountancy HND · Yaba Tech', grade: '📈 C4 → B2 improvement', emoji: '👨🏿‍💼', color: 'rgba(245,158,11,0.15)' }
	];

	onMount(() => {
		const observer = new IntersectionObserver((entries) => {
			entries.forEach(e => { if (e.isIntersecting) animateCounters(); });
		}, { threshold: 0.3 });
		const statsEl = document.getElementById('stats-section');
		if (statsEl) observer.observe(statsEl);
		return () => observer.disconnect();
	});
</script>

<svelte:head>
	<title>CollegeCBT — AI Exam Practice for Nigerian Higher Institutions | Practice Smart, Score Higher</title>
	<meta name="description" content="Unlimited AI-generated exam questions, timed WAEC-graded mock exams, and AI Readiness Score for 550+ Nigerian universities, polytechnics, and colleges of education." />
</svelte:head>

<!-- ══════════════════════════════════════ HERO ══════════════════════════════════════ -->
<section class="pt-[100px] pb-24 relative overflow-hidden" aria-labelledby="hero-heading">
	<div class="page-container text-center">
		<!-- Badge -->
		<div class="badge badge-violet text-xs mb-6 inline-flex" data-sveltekit-preload-data="off">
			🤖 Powered by Anthropic's Claude AI
		</div>

		<h1 id="hero-heading" class="font-display text-5xl sm:text-6xl lg:text-7xl leading-[1.05] tracking-tight mb-6" style="letter-spacing:-0.03em;">
			Practice Smart.
			<span style="background:linear-gradient(135deg,#a78bfa,#84cc16);-webkit-background-clip:text;-webkit-text-fill-color:transparent;">Score Higher.</span>
		</h1>

		<p class="text-white/60 text-lg sm:text-xl max-w-2xl mx-auto mb-8 leading-relaxed">
			Generate unlimited exam questions for any course in Nigerian higher institutions —
			with full explanations, timed mock exams, and AI-powered grade prediction.
		</p>

		<div class="flex flex-wrap gap-4 justify-center mb-12">
			<a href="/exam-lab" class="btn-violet px-8 py-4 text-base shadow-violet">
				🤖 Start Exam Lab — Free
			</a>
			<button on:click={() => activeModal.set('signup')} class="btn-ghost px-7 py-4 text-base">
				⏱️ Try Mock Exam →
			</button>
		</div>

		<!-- Social proof strip -->
		<div class="flex flex-wrap gap-6 justify-center items-center text-sm text-white/40">
			<span>✅ No credit card required</span>
			<span>·</span>
			<span>✅ Works for all Nigerian institutions</span>
			<span>·</span>
			<span>✅ Free plan available</span>
		</div>
	</div>
</section>

<!-- ════════════════════════════════════ STATS ════════════════════════════════════ -->
<section id="stats-section" class="py-16 relative overflow-hidden">
	<div class="page-container">
		<div class="grid grid-cols-2 md:grid-cols-4 gap-6">
			{#each [
				{ num: counters.institutions + '+', label: 'Institutions Covered', icon: '🏛️' },
				{ num: counters.questions + 'K+', label: 'Questions Generated', icon: '📝' },
				{ num: counters.students + 'K+', label: 'Active Students', icon: '👨‍🎓' },
				{ num: counters.passRate + '%', label: 'Target Pass Rate', icon: '🏆' }
			] as stat}
				<div class="glass-card p-6 text-center">
					<div class="text-3xl mb-2">{stat.icon}</div>
					<div class="font-title text-4xl sm:text-5xl" style="background:linear-gradient(135deg,#a3e635,#bef264);-webkit-background-clip:text;-webkit-text-fill-color:transparent;">
						{stat.num}
					</div>
					<div class="text-xs text-white/50 mt-1 font-medium">{stat.label}</div>
				</div>
			{/each}
		</div>
	</div>
</section>

<!-- ═══════════════════════════════════ FEATURES ═══════════════════════════════════ -->
<section id="features" class="py-20 relative" aria-labelledby="features-heading">
	<div class="page-container">
		<div class="text-center mb-14">
			<div class="section-tag">✨ Platform Features</div>
			<h2 id="features-heading" class="font-display text-4xl sm:text-5xl mb-4">
				Everything You Need to
				<span style="background:linear-gradient(135deg,#a78bfa,#84cc16);-webkit-background-clip:text;-webkit-text-fill-color:transparent;">Excel in Exams</span>
			</h2>
			<p class="text-white/50 max-w-xl mx-auto">Built specifically for Nigerian higher education students, from 100 Level to Postgraduate.</p>
		</div>

		<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
			{#each features as feat}
				<div class="feature-card">
					<div class="text-4xl mb-4">{feat.icon}</div>
					<h3 class="font-bold text-lg mb-2">{feat.title}</h3>
					<p class="text-white/50 text-sm leading-relaxed">{feat.desc}</p>
					<div class="mt-4 pt-4 border-t border-white/5">
						<a href="/exam-lab" class="text-xs font-semibold transition-colors hover:opacity-80" style="color:{feat.color};">Try it free →</a>
					</div>
				</div>
			{/each}
		</div>
	</div>
</section>

<!-- ═══════════════════════════════════ CURRICULUM  ═══════════════════════════════════ -->
<section id="curriculum" class="py-20" aria-labelledby="curriculum-heading">
	<div class="page-container">
		<div class="text-center mb-10">
			<div class="section-tag">📚 Course Browser</div>
			<h2 id="curriculum-heading" class="font-display text-4xl sm:text-5xl mb-4">
				<span style="background:linear-gradient(135deg,#a78bfa,#84cc16);-webkit-background-clip:text;-webkit-text-fill-color:transparent;">550+ Institutions.</span><br />Every Course. Every Level.
			</h2>
			<p class="text-white/50 max-w-xl mx-auto">Select your institution type and browse the full curriculum available on CollegeCBT.</p>
		</div>

		<!-- Institution Type Tabs -->
		<div class="flex gap-2 mb-6 p-1.5 rounded-2xl border border-white/10 bg-black/20 overflow-x-auto">
			{#each INSTITUTION_TYPES as inst}
				<button
					on:click={() => selectedInst = inst}
					class="flex-1 min-w-max py-2.5 px-4 rounded-xl text-sm font-semibold transition-all whitespace-nowrap"
					class:cur-tab={selectedInst === inst}
					class:off-tab={selectedInst !== inst}
				>
					{inst}
				</button>
			{/each}
		</div>

		<!-- Search -->
		<div class="mb-6">
			<input
				type="text"
				bind:value={courseSearch}
				class="form-input max-w-md"
				placeholder="Search courses..."
			/>
		</div>

		<!-- Course Grid -->
		<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
			{#each filteredCourses as course}
				<div class="glass-card p-4 flex items-center justify-between gap-3 hover:border-violet-DEFAULT hover:border-opacity-50 transition-all group">
					<div>
						<div class="text-sm font-semibold text-white/90 group-hover:text-white transition-colors">{course}</div>
						<div class="text-xs text-white/40 mt-0.5">{selectedInst}</div>
					</div>
					<div class="flex gap-2 flex-shrink-0">
						<button
							on:click={() => goToLab(course, 'lab')}
							class="text-violet-light hover:text-white text-xs font-semibold px-3 py-1.5 rounded-lg bg-violet-DEFAULT/10 hover:bg-violet-DEFAULT/30 transition-all"
						>
							Practice
						</button>
						<button
							on:click={() => goToLab(course, 'mock')}
							class="text-lime-DEFAULT hover:text-white text-xs font-semibold px-3 py-1.5 rounded-lg bg-lime-DEFAULT/10 hover:bg-lime-DEFAULT/30 transition-all"
						>
							Mock
						</button>
					</div>
				</div>
			{:else}
				<div class="col-span-full text-center text-white/40 py-8">No courses match your search.</div>
			{/each}
		</div>
	</div>
</section>

<!-- ═══════════════════════════════════ HOW IT WORKS ═══════════════════════════════════ -->
<section class="py-20" aria-labelledby="how-heading">
	<div class="page-container">
		<div class="text-center mb-14">
			<div class="section-tag">🚀 Getting Started</div>
			<h2 id="how-heading" class="font-display text-4xl sm:text-5xl mb-4">Study Smarter in
				<span style="background:linear-gradient(135deg,#a78bfa,#84cc16);-webkit-background-clip:text;-webkit-text-fill-color:transparent;">3 Simple Steps</span>
			</h2>
		</div>
		<div class="grid grid-cols-1 md:grid-cols-3 gap-8">
			{#each [
				{ step: '01', icon: '🎓', title: 'Select Your Course', desc: 'Choose your institution type, course, level, and difficulty. CollegeCBT supports 550+ institutions.' },
				{ step: '02', icon: '🤖', title: 'Generate & Practice', desc: 'Claude AI generates contextual, curriculum-aligned questions with full distractor explanations instantly.' },
				{ step: '03', icon: '📈', title: 'Track Your Score', desc: 'Review your AI Readiness Score, grade prediction, topic heatmap, and personalized study recommendations.' }
			] as item}
				<div class="text-center">
					<div class="relative inline-block mb-6">
						<div class="w-20 h-20 rounded-2xl flex items-center justify-center text-4xl mx-auto" style="background:rgba(124,58,237,0.12);border:1px solid rgba(124,58,237,0.2);">{item.icon}</div>
						<div class="absolute -top-2 -right-2 w-8 h-8 rounded-full bg-violet-DEFAULT flex items-center justify-center text-xs font-bold font-mono">{item.step}</div>
					</div>
					<h3 class="font-bold text-xl mb-2">{item.title}</h3>
					<p class="text-white/50 text-sm leading-relaxed">{item.desc}</p>
				</div>
			{/each}
		</div>
	</div>
</section>

<!-- ═══════════════════════════════════ TESTIMONIALS ═══════════════════════════════════ -->
<section id="testimonials" class="py-20" aria-labelledby="test-heading">
	<div class="page-container">
		<div class="text-center mb-12">
			<div class="section-tag">💬 Student Success Stories</div>
			<h2 id="test-heading" class="font-display text-4xl sm:text-5xl mb-4">
				Real Students. <span style="background:linear-gradient(135deg,#a78bfa,#84cc16);-webkit-background-clip:text;-webkit-text-fill-color:transparent;">Real Results.</span>
			</h2>
			<p class="text-white/50 max-w-xl mx-auto">Nigerian undergraduates across universities and polytechnics sharing their CollegeCBT experience.</p>
		</div>
		<div class="grid grid-cols-1 md:grid-cols-3 gap-6">
			{#each testimonials as t}
				<div class="glass-card p-6 relative">
					<div class="absolute top-4 right-5 font-display text-5xl text-violet-DEFAULT/20 leading-none">"</div>
					<p class="text-white/80 text-sm italic leading-relaxed mb-6">"{t.quote}"</p>
					<div class="flex items-center gap-3">
						<div class="w-10 h-10 rounded-full flex items-center justify-center text-xl flex-shrink-0" style="background:{t.color};">{t.emoji}</div>
						<div>
							<div class="font-bold text-sm">{t.name}</div>
							<div class="text-xs text-white/40">{t.meta}</div>
							<div class="text-xs font-mono font-semibold text-lime-DEFAULT mt-0.5">{t.grade}</div>
						</div>
					</div>
				</div>
			{/each}
		</div>
	</div>
</section>

<!-- ═══════════════════════════════════ FAQ ═══════════════════════════════════ -->
<section id="faq" class="py-20" aria-labelledby="faq-heading">
	<div class="page-container max-w-3xl">
		<div class="text-center mb-10">
			<div class="section-tag">❓ Common Questions</div>
			<h2 id="faq-heading" class="font-display text-4xl sm:text-5xl mb-4">
				Questions About <span style="background:linear-gradient(135deg,#a78bfa,#84cc16);-webkit-background-clip:text;-webkit-text-fill-color:transparent;">CollegeCBT</span>
			</h2>
		</div>
		<div class="space-y-3">
			{#each faqs as faq, i}
				<div class="glass-card overflow-hidden">
					<button
						on:click={() => openFaq = openFaq === i ? -1 : i}
						class="w-full text-left px-5 py-4 flex items-center justify-between gap-4 font-semibold text-sm hover:text-violet-light transition-colors"
						aria-expanded={openFaq === i}
					>
						<span>{faq.q}</span>
						<span class="flex-shrink-0 text-lg transition-transform duration-300" class:rotate-45={openFaq === i}>+</span>
					</button>
					{#if openFaq === i}
						<div class="px-5 pb-4 text-sm text-white/60 leading-relaxed border-t border-white/5 pt-3">
							{faq.a}
						</div>
					{/if}
				</div>
			{/each}
		</div>
	</div>
</section>

<!-- ═══════════════════════════════════ CTA BANNER ═══════════════════════════════════ -->
<section class="py-20">
	<div class="page-container">
		<div class="rounded-3xl p-10 md:p-16 text-center relative overflow-hidden" style="background:linear-gradient(135deg,rgba(124,58,237,0.22),rgba(132,204,22,0.08));border:1px solid rgba(124,58,237,0.3);">
			<div class="text-6xl mb-4">🎓</div>
			<h2 class="font-display text-4xl sm:text-5xl mb-4">Ready to Score A1?</h2>
			<p class="text-white/60 max-w-lg mx-auto mb-8">Join 12,000+ Nigerian students who use CollegeCBT to practise smarter and achieve their target grades.</p>
			<div class="flex flex-wrap gap-4 justify-center">
				<button on:click={() => activeModal.set('signup')} class="btn-violet px-8 py-4 text-base shadow-violet">
					Start Free Today — No Credit Card
				</button>
				<a href="/exam-lab" class="btn-ghost px-7 py-4 text-base">
					Try Exam Lab First →
				</a>
			</div>
		</div>
	</div>
</section>

<!-- ═══════════════════════════════════ FOOTER ═══════════════════════════════════ -->
<footer class="border-t border-white/8 py-14" style="background:rgba(0,0,0,0.5);">
	<div class="page-container">
		<div class="grid grid-cols-2 md:grid-cols-4 gap-8 mb-10">
			<div class="col-span-2 md:col-span-1">
				<a href="/" class="font-display text-2xl block mb-3" style="background:linear-gradient(135deg,#fff 40%,#a78bfa);-webkit-background-clip:text;-webkit-text-fill-color:transparent;">
					College<span style="-webkit-text-fill-color:#84cc16;">CBT</span>
				</a>
				<p class="text-xs text-white/40 leading-relaxed max-w-[240px] mb-4">
					AI-powered exam practice for every Nigerian higher education student. Results as a Service.
				</p>
				<div class="flex items-center gap-2">
					<div class="w-2 h-2 rounded-full bg-lime-DEFAULT animate-blink"></div>
					<span class="text-xs text-lime-DEFAULT font-semibold">System Operational</span>
				</div>
			</div>
			<div>
				<h3 class="font-bold text-sm mb-4">Platform</h3>
				<div class="space-y-2.5">
					{#each ['Exam Lab', 'Mock Exams', 'Dashboard', 'Pricing', 'Curriculum'] as link}
						<a href="/{link.toLowerCase().replace(' ', '-')}" class="block text-sm text-white/40 hover:text-violet-light transition-colors">{link}</a>
					{/each}
				</div>
			</div>
			<div>
				<h3 class="font-bold text-sm mb-4">Institutions</h3>
				<div class="space-y-2.5">
					{#each ['Universities (NUC)', 'Polytechnics (NBTE)', 'Colleges of Education', 'IEI / Technical'] as link}
						<a href="/curriculum" class="block text-sm text-white/40 hover:text-violet-light transition-colors">{link}</a>
					{/each}
				</div>
			</div>
			<div>
				<h3 class="font-bold text-sm mb-4">Company</h3>
				<div class="space-y-2.5">
					{#each ['About CollegeCBT', 'Privacy Policy', 'Terms of Service', 'Contact Us', 'Support'] as link}
						<a href="/{link.toLowerCase().replace(/ /g, '-')}" class="block text-sm text-white/40 hover:text-violet-light transition-colors">{link}</a>
					{/each}
				</div>
			</div>
		</div>
		<div class="pt-6 border-t border-white/8 flex flex-col sm:flex-row items-center justify-between gap-4">
			<p class="text-xs text-white/30">© {new Date().getFullYear()} CollegeCBT. All rights reserved. Powered by Anthropic Claude AI.</p>
			<p class="text-xs text-white/30">Built for Nigerian higher education students</p>
		</div>
	</div>
</footer>

<style>
	.cur-tab {
		background: #7c3aed;
		color: #fff;
		box-shadow: 0 4px 20px rgba(124, 58, 237, 0.4);
	}
	.off-tab {
		color: #94a3b8;
	}
	.off-tab:hover {
		color: #fff;
		background: rgba(124, 58, 237, 0.15);
	}
</style>
